server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #配置Nacos地址
        # server-addr: localhost:8848
      # 换成nginx的1111端口，做集群
        server-addr: 192.168.73.11:1111


management:
  endpoints:
    web:
      exposure:
        include: '*'

